CREATE TABLE "doctors" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "doctors_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"imageURL" varchar(255),
	"fullName" varchar(255) NOT NULL,
	"age" integer NOT NULL,
	"gender" integer NOT NULL,
	"email" varchar(255) NOT NULL,
	"address" varchar(255) NOT NULL,
	"phoneNumber" varchar(255) NOT NULL,
	"pmdcRedgNo" varchar(255) NOT NULL,
	"pmdcRedgDate" timestamp NOT NULL,
	"medicalDegree" integer NOT NULL,
	"postGraduateDegree" integer NOT NULL,
	"specialization" integer NOT NULL,
	"yearsOfExperience" integer NOT NULL,
	"pmdcLicenseDocumentURL" varchar(255) NOT NULL,
	"verificationDocumentType" integer NOT NULL,
	"verificationDocumentNumber" varchar(255) NOT NULL,
	"verificationDocumentURL" varchar(255) NOT NULL,
	"password" varchar(255) NOT NULL,
	"authenticInformationConsent" boolean NOT NULL,
	"licenseVerificationConsent" boolean NOT NULL,
	"termsAgreementConsent" boolean NOT NULL,
	"dataUsageConsentConsent" boolean NOT NULL,
	"status" integer DEFAULT 0 NOT NULL,
	"verifiedAt" timestamp with time zone,
	"createdAt" timestamp with time zone DEFAULT now() NOT NULL,
	"updatedAt" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "doctors_email_unique" UNIQUE("email"),
	CONSTRAINT "doctors_phoneNumber_unique" UNIQUE("phoneNumber"),
	CONSTRAINT "doctors_verificationDocumentNumber_unique" UNIQUE("verificationDocumentNumber")
);
